### ISSUE TITLE
Popline appears off-screen for highlights at the top of a document

### ISSUE THREAD

**Issue by roryok** [kenshin54/popline#30]
This is reproducible on the demo page. Simply reduce the window to a size where scrolling is required (or alternatively add more content so that scrolling is required) and scroll part of the way down the page. Select the sentence at the top of the window. Popline appears out of screen bounds
![2014-10-24 09_22_50-popline - an html5 rich-text-editor toolbar](https://cloud.githubusercontent.com/assets/354407/4766881/36642138-5b57-11e4-93f8-6a475c82a2bd.png)

**Comment by donShakespeare** [comment]
The patch never came? Now this is highly welcome. Respecting Viewport is important... I will try and patch it.
@kenshin54 , awesome plugin

**Comment by donShakespeare** [comment]
In `mouseup: function(event) {...` and ` keyup: function(event) {...`
add `if (top < document.body.scrollTop) top = document.body.scrollTop + 10;`
just before ` return {left: left, top: top};`

This should fix the top problem

**Comment by roryok** [comment]
Hi guys, sorry I never committed the patch, got sidetracked by another project and forgot all about it. This is pretty much what I did though

**Comment by roryok** [comment]
Actually that fix positions the bar on top of the word, I had a better fix. I'll commit to my fork in the next hour and issue a pull request. Which will be a new experience for me =)

**Comment by donShakespeare** [comment]
You are right, bottom seems better.
And for off screen to the right, any solution?
I am using

```
  if (left + bar.width() > $(window).width()) {
            left = $(window).width() - bar.width();
          }
```
