### ISSUE TITLE
Add indent support

### ISSUE THREAD

**Issue by July-G** [kenshin54/popline#32]

**Comment by kenshin54** [comment]
@July-G, Popline support indent and outdent, see the image i attached. 
![image](https://cloud.githubusercontent.com/assets/556914/6689096/0d2ad6be-ccf3-11e4-9512-24ce8e5eee11.png)
![image](https://cloud.githubusercontent.com/assets/556914/6689103/1d319912-ccf3-11e4-81c0-1bc2c67872e8.png)
