### ISSUE TITLE
Popline appears even on non-contenteditable element

### ISSUE THREAD

**Issue by jackdeguest** [kenshin54/popline#33]
Hello,

I have a floating window composed of an unordered list each containing a div that when double-clicked upon becomes editable. I then call on Popline by creating an instance clickedDiv.popline({position: "fixed"}). However when clicked outside the div, it ceases to be editable, but there is no documented mechanism to destroy the generated instance.
Then when clicked on another div (i.e. in another li element), Popline pops up, although the div does not have the "content editable" attribute.
I beileve this could be solved if there was a way to dynamically create Popline instance and destroy them as necessary.

Thank you!

**Comment by Errvald** [comment]
Even in the demo page it shows up everywhere you highlight even outside the editable element.

**Comment by kenshin54** [comment]
Hey, guys, sorry for the late response on this issue. The bug has been fixed in the master branch. Please check it out.
