### ISSUE TITLE
Make popline editor buttons and view buttons totaly optional

### ISSUE THREAD

**Issue by donShakespeare** [kenshin54/popline#37]
The concept of having a bubble appear on text-select is pure genius, jQuery-wise.
But in my case I have a powerful WYSIWYG already, and don't need the one that popline provides.

In the popline.js I killed 

//makeButtons.call(this, this.bar, $.popline.buttons);

And did this

      init: function() {
        this.bar = $("#tinymceWrapperBubbleNP").addClass("popline");

Now I have a beautiful Tinymce 4 real floating toolbar for contenteditables

**Comment by kenshin54** [comment]
Hi, if I understand you correctly, you just want a floating bar, but without any buttons. I think this is not the  common use case of Popline and not the main problem that Popline want to solve. You can do this with you hack way if you like, but I have no plan to support this in a short time.

Thanks
